type: x-username-schema
describedBy:
  queryParameters:
    username:
      description: |
        The GeoNames Web Service Identifier. Each subscriber to GeoNames Web Services is uniquely
        identified by a username and every request to Web services requires this username.
